<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="stylesheet" href="/public/css/bootstrap.min.css" type="text/css"/>
		<link rel="stylesheet" href="/public/css/style.css" type="text/css"/>
		<script type="text/javascript" src="/public/js/jquery-1.10.2.min.js"></script>
		<script type="text/javascript" src="/public/js/bootstrap.min.js"></script>
		<?php
		echo $this -> headTitle();
		echo $this -> headLink();
		echo $this -> headScript();
		?>

	</head>
	<body>
		<?php echo $this->layout()->content?>
	</body>
</html>