<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap core CSS -->
    <script type="text/javascript" src="/public/js/jquery-1.10.2.min.js"></script>
    <link href="/public/css/bootstrap.css" rel="stylesheet">

    <!-- Add custom CSS here -->
    <link href="/public/css/sb-admin.css" rel="stylesheet">
    <link href="/public/css/style.css" rel="stylesheet">
    
    <link rel="stylesheet" href="/public/font-awesome/css/font-awesome.min.css">
    <!-- Page Specific CSS -->
    <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
    
    	<?php
		echo $this -> headTitle();
		echo $this -> headLink();
		?>
    
    
  </head>

  <body>

    <div id="wrapper">

      <!-- Sidebar -->
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">Capital Protection</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-table"></i> Hedge Funds <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/hedgefunds/">View All</a></li>
                <li><a href="/hedgefunds/setup/">Add New HedgeFund</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-table"></i> Portfolios <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="/portfolio/">View All</a></li>
                <li><a href="/portfolio/setup/">Setup Portfolio</a></li>
              </ul>
            </li>
            
          </ul>

          <ul class="nav navbar-nav navbar-right navbar-user">

            <li class="dropdown user-dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i> <?php echo $this->manager["first_name"]." ".$this->manager["last_name"]?><b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#"><i class="icon-user"></i> Profile</a></li>
                <li><a href="#"><i class="icon-gear"></i> Settings</a></li>
                <li class="divider"></li>
                <li><a href="/users/logout/"><i class="icon-power-off"></i> Log Out</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>

      <div id="page-wrapper">
		<?php echo $this->layout()->content?>
      </div><!-- /#page-wrapper -->

    </div><!-- /#wrapper -->

    <!-- Bootstrap core JavaScript -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="/public/js/bootstrap.js"></script>
    <script src="/public/js/typeahead.min.js"></script>
    
    <?php
		echo $this -> headScript();
    ?>
    <!-- Page Specific Plugins -->
  </body>
</html>