<div class="container">
	<div class="col-lg-2"></div>
	<form class="form-horizontal login_form bs-example col-lg-8" role="form" action="/users/signin/" method="POST">
		<?php
		if ($this->error!=""){
			?>
			<div class="error">
				<?php echo $this->error?>
			</div>
			<?php
		}?>
		
		<div class="form-group">
			<label for="inputEmail1" class="col-lg-2 control-label">Username</label>
			<div class="col-lg-10">
				<?php echo $this -> form -> username -> renderViewHelper();?>
			</div>
		</div>
		<div class="form-group">
			<label for="inputPassword1" class="col-lg-2 control-label">Password</label>
			<div class="col-lg-10">
				<?php echo $this -> form -> password -> renderViewHelper();?>
			</div>
		</div>
		<!--
		<div class="form-group">
			<div class="col-lg-offset-2 col-lg-10">
				<div class="checkbox">
					<label>
						<input type="checkbox">
						Remember me </label>
				</div>
			</div>
		</div>
		-->
		<div class="form-group">
			<div class="col-lg-offset-2 col-lg-10">
				<button type="submit" class="btn btn-default">
					Sign in
				</button>
			</div>
		</div>
	</form>
	<div class="col-lg-2"></div>
</div>
