<?php
$elements = $this->form->getElements();
?>




<div class="row">
	<div class="col-lg-12">
		<h1>Setup New Fund</h1>
		<ol class="breadcrumb">
			<li>
				<a href="/"> <i class="icon-home"></i> Home</a>
			</li>
			<li>
				<a href="/hedgefunds/"> <i class="icon-table"></i> Hedge Funds</a>
			</li>
			<li class="active">
				<i class="icon-table"></i> Setup HedgeFund
			</li>
			
		</ol>
	</div>
	<div class="alert alert-info alert-dismissable">
		<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
			Use the Tab to navigate through different sections. Section marked with * have required fields.
	</div>
</div>

<form role="form" action="/hedgefunds/create" method="POST" id="hedgefund_setup_form">
	
		
	
	<div class="row">
		<div id="save_result"></div>
		<div class="container-fluid clear-fix" style="clear:both;margin-bottom:15px;">
			<button class="btn btn-primary" type="submit">Save New Fund</button>
		</div>
	</div>
	
	<ul id="myTab" class="nav nav-tabs" style="margin-bottom:15px">
	    <li class="active"><a href="#basic" data-toggle="tab">Basic Information *</a></li>
	    <li class=""><a href="#info_2" data-toggle="tab">Information 2 *</a></li>
	    <li class=""><a href="#people" data-toggle="tab">People</a></li>
	    <li class=""><a href="#others" data-toggle="tab">Others</a></li>
	    
	  </ul>
	 
	<div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active in" id="basic">
        	<div class="row">
        		<div class="col-lg-4">
        			<?php 
					$basic_info = array("fund_name", "general_partner_fname", "general_partner_lname", "general_partner_title", "manager_fname", "manager_lname", "manager_title", "street_1", "street_2", "city", "state", "country_id", "continent_id", "phone", "fax", "email", "contact_person_fname", "contact_person_lname", "contact_person_title");
					foreach($elements as $element){
						if (!in_array($element->getName(), $basic_info)){
							continue;
						}
						?>
						<div class="form-group">
							
							<label for="<?php echo $element->getName()?>"><?php echo $element->getLabel()?>
								<?php
									if ($element->isRequired()){
										?>
										<span style="color:#ff0000">*</span>
										<?php
									}
								?>
								
							</label>
							<?php echo $element->renderViewHelper()?>
						</div>	
						<?php
					}
					?>
        		</div>

        	</div>
        
        
        </div>
        <div class="tab-pane fade" id="info_2">
        	<div class="row">
        		<div class="col-lg-4">
        			<?php 
					$in_elements = array("firm_assets", "fund_assets", "primary_strategy", "secondary_strategy", "secondary_strategy_2", "description", "onshore_offshore", "return_start", "minimum_investment", "management_fee", "incentive_fee", "early_redemption_fee", "other_fee", "capital_addition", "capital_redemption", "lockup", "hurdle_rate", "high_watermark");
					foreach($elements as $element){
						if (!in_array($element->getName(), $in_elements)){
							continue;
						}
						?>
						<div class="form-group">
							<label for="<?php echo $element->getName()?>"><?php echo $element->getLabel()?>
								<?php
									if ($element->isRequired()){
										?>
										<span style="color:#ff0000">*</span>
										<?php
									}
								?>
							</label><br/>
							<?php echo $element->renderViewHelper()?>
						</div>	
						<?php
					}
					?>
        		</div>
        	</div>
        </div>
        <div class="tab-pane fade" id="people">
        	<div class="row">
        		<div class="col-lg-4">
        			<?php 
						$in_elements = array("legal_counsel_fname", "legal_counsel_lname", "legal_counsel_title", "administrator_fname", "administrator_lname", "administrator_title", "custodian_fname", "custodian_lname", "custodian_title", "accountant_fname", "accountant_lname", "accountant_title", "prime_broker_fname", "prime_broker_lname", "prime_broker_title");
						
						
						foreach($elements as $element){
							if (!in_array($element->getName(), $in_elements)){
								continue;
							}
							?>
							<div class="form-group">
								<label for="<?php echo $element->getName()?>"><?php echo $element->getLabel()?>
									<?php
										if ($element->isRequired()){
											?>
											<span style="color:#ff0000">*</span>
											<?php
										}
									?>
								</label><br/>
								<?php echo $element->renderViewHelper()?>
							</div>	
							<?php
						}
						?>
        		</div>
        	</div>
        
        </div>
        <div class="tab-pane fade" id="others">
        	<div class="row">
        		<div class="col-lg-4">
        				<?php 
						$in_elements = array("typical_net_exposure_low", "typical_net_exposure_high", "typical_percent_long_low", "typical_percent_long_high", "currency_class", "location_of_components", "open_to_investment", "assets_in_strategy", "investment_market", "investment_style", "investment_geography", "lehman_hfn_index_participant");
						
						
						foreach($elements as $element){
							if (!in_array($element->getName(), $in_elements)){
								continue;
							}
							?>
							<div class="form-group">
								<label for="<?php echo $element->getName()?>"><?php echo $element->getLabel()?>
									<?php
										if ($element->isRequired()){
											?>
											<span style="color:#ff0000">*</span>
											<?php
										}
									?>
									
								</label><br/>
								<?php echo $element->renderViewHelper()?>
							</div>	
							<?php
						}
						?>
        			
        			
        		</div>
        	</div>
        
        </div>
      </div>

</form>