<div class="row">
	<div class="col-lg-12">
		<h1>Portfolios</h1>
		<ol class="breadcrumb">
			<li>
				<a href="/"> <i class="icon-home"></i> Home</a>
			</li>
			<li class="active">
				<i class="icon-table"></i> Portfolios
			</li>
		</ol>
	</div>
</div>
<div id="save_result" class="row"></div>
<div class="row" style="overflow: hidden;margin-bottom: 15px;">
	<div class="pull-right">
		<form class="form-inline" role="form" action="/portfolio/basic-search/">
			<a href="#">Advanced Search</a>&nbsp;
			<input type="search" name="q" style="width:200px" placeholder="Enter Name of Portfolio" class="form-control"/>
			<button type="submit" class="btn btn-primary">
				Search
			</button>
		</form>
	</div>
	<a href="/portfolio/setup/" class="btn btn-default"><span class="icon-plus-sign"></span> Add New Portfolio</a>
</div>
<div class="panel panel-primary">
	<div class="panel-heading">
		List of Portfolios
	</div>
	<div class="row-fluid">
		<div class="pull-right">
			<ul class="pagination pagination-sm">
				<li class="disabled">
					<span>&laquo;</span>
				</li>
				<li class="active">
					<span>1 <span class="sr-only">(current)</span></span>
				</li>
				<li class="disabled">
					<span>&raquo;</span>
				</li>
			</ul>
		</div>
		<div class="pull-left showing">
			<p>
				Showing <strong class="start_count"></strong> - <strong class="end_count"></strong> of <strong class="total_count"></strong> portfolios
			</p>
		</div>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-bordered table-hover table-striped tablesorter" id="portfolio_list">
				<thead>
					<tr>
						<th>#</th>
						<th>Name of Portfolio</th>
						<th>Date &amp; Time Updated</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php
					foreach($this->portfolios as $key=>$portfolio){
										?>
										<tr>
											<td><?php echo $key+1
											?></td>
											<td><?php echo $portfolio["name"]
											?></td>
											<td><?php echo date("F d,Y h:i:s A", strtotime($portfolio["date_updated"]))
											?></td>
											<td><a href="/portfolio/calculate?id=<?php echo $portfolio["id"]?>" class="btn btn-xs btn-primary">View</a>&nbsp;<a href="/portfolio/update?id=<?php echo $portfolio["id"]?>" class="btn btn-xs btn-primary">Edit</a>&nbsp;<a href="/portfolio/delete?id=<?php echo $portfolio["id"]?>" class="delete_portfolio btn btn-xs btn-danger">Delete</a></td>
										</tr>
										<?php
					}
					?>
				</tbody>
			</table>
		</div>
	</div>
</div>