<div class="row">
	<div class="col-lg-12">
		<h1>Update Portfolio Information</h1>
		<ol class="breadcrumb">
			<li>
				<a href="/"> <i class="icon-home"></i> Home</a>
			</li>
			<li>
				<a href="/portfolio/"><i class="icon-table"></i> Portfolios</a>
			</li>
			<li class="active">
				<i class="icon-table"></i> Setup Portfolio
			</li>
		</ol>
	</div>
</div>
<div id="save_result" class="row"></div>
<div class="alert alert-info">
	<strong>Heads up!</strong> Enter the required information to get started.
</div>
<form class="form-horizontal col-lg-8 " action="/portfolio/save" method="POST" id="setupForm">
	<?php echo $this -> form -> id -> renderViewHelper();?>

	<div class="form-group">
		<label for="inputName" class="col-lg-3 control-label">Name</label>
		<div class="col-lg-9">
			<?php echo $this -> form -> name -> renderViewHelper();?>
		</div>
	</div>
	<div class="form-group">
		<label for="inputEquity" class="col-lg-3 control-label">Initial Equity Investment</label>
		<div class="col-lg-9">
			<?php echo $this -> form -> initial_equity -> renderViewHelper();?>
		</div>
	</div>
	<div class="form-group">
		<label class="col-lg-3 control-label">Leverage</label>
		<div class="col-lg-9">
			<?php echo $this -> form -> leverage -> renderViewHelper();?>
		</div>
	</div>
	<div class="form-group">
		<label for="inputLeverageBankCost" class="col-lg-3 control-label">Leverage Bank Cost (in basis pts)</label>
		<div class="col-lg-9">
			<?php echo $this -> form -> leverage_bank_cost -> renderViewHelper();?>
		</div>
	</div>
	<div class="form-group">
		<label for="inputAdditionalLeverageBankCost" class="col-lg-3 control-label">Additional Leverage Bank Costs</label>
		<div class="col-lg-9">
			<?php echo $this -> form -> additional_leverage_bank_cost -> renderViewHelper();?>
		</div>
	</div>
	<div class="form-group">
		<label for="inputBankLeverage" class="col-lg-3 control-label">Bank Leverage</label>
		<div class="col-lg-9">
			<?php echo $this -> form -> bank_leverage -> renderViewHelper();?>
		</div>
	</div>
	<div class="form-group">
		<label class="col-lg-3 control-label">Show results net of Fund of Funds fees</label>
		<div class="col-lg-9">
			<?php echo $this -> form -> show_results_net_fund -> renderViewHelper();?>
		</div>
	</div>
	<div class="form-group">
		<label class="col-lg-3 control-label">Fund of Funds Management fee</label>
		<div class="col-lg-9">
			<?php echo $this -> form -> fund_of_funds_management_fee -> renderViewHelper();?>
		</div>
	</div>
	<div class="form-group">
		<label class="col-lg-3 control-label">Fund of Funds Performance fee</label>
		<div class="col-lg-9">
			<?php echo $this -> form -> fund_of_funds_performance_fee -> renderViewHelper();?>
		</div>
	</div>
	<div class="form-group">
		<label class="col-lg-3 control-label">Leverage Ratio (debt/equity)</label>
		<div class="col-lg-9">
			<?php echo $this -> form -> leverage_ratio_id -> renderViewHelper();?>
		</div>
	</div>
	<div class="form-group">
		<div class="col-lg-3"></div>
		<div class="col-lg-9">
			<button type="submit" class="btn btn-primary">
				Save and Proceed
			</button>
		</div>
	</div>
</form>